=== brl/netifera/platform/com.netifera.platform.net/com.netifera.platform.net.services.detection/ServiceTriggers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://netifera.com/ServiceTrigger" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:netifera="http://netifera.com/ServiceTrigger">

    <complexType name="Enpdoint">
    	<simpleContent>
    		<extension base="string">
    			<attribute name="protocol" use="required">
    				<annotation>
    					<documentation>
    						The value of this element for the protocol
    						types TCP,UDP and SSL is a port range
    					</documentation>
    				</annotation>
    				<simpleType>
    					<restriction base="string">
    						<enumeration value="udp"></enumeration>
    						<enumeration value="tcp"></enumeration>
    						<enumeration value="ssl"></enumeration>
    					</restriction>
    				</simpleType>
    			</attribute>

    		</extension>
    	</simpleContent>
    </complexType>

    <complexType name="ServiceTrigger">
        <sequence>
    		<element name="Endpoint" type="netifera:Enpdoint" maxOccurs="unbounded" minOccurs="1">
    		</element>
    	</sequence>
    	<attribute name="name" type="string" use="required">
    		<annotation>
    			<documentation>Descriptive name of the test</documentation>
    		</annotation></attribute>
    	<attribute name="data" type="hexBinary" use="optional">
    		<annotation>
    			<documentation>The data that is actually sent</documentation>
    		</annotation></attribute>
    	<attribute name="timeout" type="integer" use="optional">
    		<annotation>
    			<documentation>Timeout in milliseconds</documentation>
    		</annotation></attribute>
    </complexType>

    <complexType name="ServiceTriggers">
    	<sequence>
    		<element name="ServiceTrigger" type="netifera:ServiceTrigger" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
        <attribute name="name" type="string"></attribute>
        <attribute name="date" type="dateTime"></attribute>
    </complexType>
    
    <element name="ServiceTriggers" type="netifera:ServiceTriggers"></element>
</schema>

=== brl/netifera/platform/com.netifera.platform.net/com.netifera.platform.net.services.detection/Triggers.xml
<?xml version="1.0" encoding="UTF-8"?>
<netifera:ServiceTriggers xmlns:netifera="http://netifera.com/ServiceTrigger" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://netifera.com/ServiceTrigger ServiceTriggers.xsd ">
<ServiceTrigger timeout="6000" name="SSL" data="808001030100570000002000001600001300000a0700c000006600000700000500000405008003008001008008008000006500006400006300006200006100006000001500001200000906004000001400001100000800000600000304008002008063b9b919c02bae90744c73eb8bcfd855ead069821bef23c3399b8eb2493c5a79">
<Endpoint protocol="tcp">443</Endpoint>
</ServiceTrigger>
<ServiceTrigger timeout="6000" name="FtpUser" data="55534552206674700d0a">
<Endpoint protocol="tcp">21,990</Endpoint>
</ServiceTrigger>
<ServiceTrigger timeout="6000" name="HttpGet" data="474554202f20485454502f312e300d0a0d0a">
<Endpoint protocol="tcp">80-81,88,443,1080,8000,8080-8081,8118,8888</Endpoint>
</ServiceTrigger>
<ServiceTrigger timeout="6000" name="FiveNewLines" data="0a0a0a0a0a">
<Endpoint protocol="tcp">3306</Endpoint>
</ServiceTrigger>
<ServiceTrigger timeout="6000" name="TNSConnect" data="005a0000010000000136012c000008007fffa30a000001000020003a0000000000000000000000000000000006fc00000002000000000000000028434f4e4e4543545f444154413d28434f4d4d414e443d76657273696f6e2929">
<Endpoint protocol="tcp">1521-1529</Endpoint>
</ServiceTrigger>
<ServiceTrigger timeout="6000" name="TerminalServer" data="0300000b06e00000000000">
<Endpoint protocol="tcp">3389</Endpoint>
</ServiceTrigger>
<ServiceTrigger timeout="6000" name="SmtpHelo" data="48454c4f206d61696c0d0a">
<Endpoint protocol="tcp">25,465</Endpoint>
</ServiceTrigger>
<ServiceTrigger timeout="6000" name="BlankLineCRLF" data="0d0a">
<Endpoint protocol="tcp">110,143,995</Endpoint>
</ServiceTrigger>
<ServiceTrigger timeout="6000" name="MSSQL" data="1201003400000000000015000601001b000102001c000c0300280004ff080001550000004d5353514c536572766572004e53464f">
<Endpoint protocol="tcp">1433</Endpoint>
</ServiceTrigger>
<ServiceTrigger timeout="6000" name="DNSVersion" data="0006010000010000000000000776657273696f6e0462696e640000100003">
<Endpoint protocol="udp">53</Endpoint>
</ServiceTrigger>
<ServiceTrigger timeout="6000" name="RPCUDP" data="12345678000000000000000200000000000000000000000000000000000000000000000000000000">
<Endpoint protocol="udp">111,2049,4045,32771-32850</Endpoint>
</ServiceTrigger>
<ServiceTrigger timeout="6000" name="RPCTCP" data="8000002812345678000000000000000200000000000000000000000000000000000000000000000000000000">
<Endpoint protocol="tcp">111,2049,4045,32771-32850</Endpoint>
</ServiceTrigger>
<ServiceTrigger timeout="6000" name="Snmpv1Public" data="302602010004067075626c6963a11902041f3c1d65020100020100300b300906052b060102010500">
<Endpoint protocol="udp">161</Endpoint>
</ServiceTrigger>
<ServiceTrigger timeout="6000" name="XDMCP" data="0001000200090100065a6172646f5a">
<Endpoint protocol="udp">177</Endpoint>
</ServiceTrigger>
<ServiceTrigger timeout="6000" name="OpenVPN" data="38835f90640513c7960000000000">
<Endpoint protocol="udp">1194</Endpoint>
</ServiceTrigger>
<ServiceTrigger timeout="6000" name="Radius" data="0100001400000000000000000000000000000000">
<Endpoint protocol="udp">1812</Endpoint>
</ServiceTrigger>
<ServiceTrigger timeout="6000" name="SSDP" data="4d2d534541524348202a20485454502f312e310d0a53543a20737364703a616c6c0d0a4d583a20343030300d0a4d414e3a2022737364703a646973636f766572220d0a0d0a">
<Endpoint protocol="udp">1900</Endpoint>
</ServiceTrigger>
<ServiceTrigger timeout="6000" name="SIP" data="">
<Endpoint protocol="udp">5060</Endpoint>
</ServiceTrigger>
<ServiceTrigger timeout="6000" name="NetBIOS" data="79080000000100000000000020434b4141414141414141414141414141414141414141414141414141414141410000210001">
<Endpoint protocol="tcp">137,138,139</Endpoint>
<Endpoint protocol="udp">135,137,138,139</Endpoint>
</ServiceTrigger>
<ServiceTrigger timeout="6000" name="SMB" data="00000085ff534d4272000000001853c80000000000000000000000000000fffe00000000006200025043204e4554574f524b2050524f4752414d20312e3000024c414e4d414e312e30000257696e646f777320666f7220576f726b67726f75707320332e316100024c4d312e325830303200024c414e4d414e322e3100024e54204c4d20302e313200">
<Endpoint protocol="tcp">135,445</Endpoint>
</ServiceTrigger>
<ServiceTrigger timeout="6000" name="SSHVersion" data="5353482d322e302d4f70656e535348">
<Endpoint protocol="tcp">22</Endpoint>
</ServiceTrigger>
<ServiceTrigger timeout="6000" name="Telnet" data="fffb03">
<Endpoint protocol="tcp">23</Endpoint>
</ServiceTrigger>
<ServiceTrigger timeout="6000" name="LDAP" data="300c020101600702010204008000">
<Endpoint protocol="tcp">389</Endpoint>
</ServiceTrigger>
<ServiceTrigger timeout="6000" name="Wait" data="">
<Endpoint protocol="tcp">79,119</Endpoint>
</ServiceTrigger>
</netifera:ServiceTriggers>
